---
abstract: 'Catalyst based monitoring web interface'
author:
  - 'Sven Nierlein, 2010-2012, <nierlein@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Thruk
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Catalyst: 5.9001
  Catalyst::Authentication::User::Hash: 0
  Catalyst::Controller: 0
  Catalyst::Devel: 0
  Catalyst::Exception: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::Cache: 0
  Catalyst::Plugin::Compress: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::CustomErrorMessage: 0
  Catalyst::Plugin::Redirect: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0.3
  Catalyst::Runtime: 0
  Catalyst::ScriptRunner: 0
  Catalyst::Utils: 0
  Catalyst::View: 0
  Catalyst::View::Excel::Template::Plus: 0
  Catalyst::View::GD: 0
  Catalyst::View::JSON: 0
  Catalyst::View::PDF::Reuse: 0
  Catalyst::View::TT: 0
  CatalystX::LeakChecker: 0
  Chart::Clicker: 0
  Chart::Clicker::Data::DataSet: 0
  Chart::Clicker::Data::Marker: 0
  Chart::Clicker::Data::Range: 0
  Chart::Clicker::Data::Series: 0
  Chart::Clicker::Decoration::Legend::Tabular: 0
  Chart::Clicker::Renderer::Pie: 0
  Chart::Clicker::Renderer::StackedBar: 0
  Class::Accessor::Fast: 0
  Class::C3::Adopt::NEXT: 0
  Class::C3::XS: 0
  Class::Data::Inheritable: 0
  Class::Inspector: 0
  Config::Any: 0
  Config::General: 0
  Data::Page: 0
  Date::Calc: 6.3
  Date::Calc::XS: 0
  Date::Manip: 0
  Excel::Template::Plus: 0
  FCGI: 0
  FCGI::ProcManager: 0
  FCGI::ProcManager::MaxRequests: 0
  File::BOM: 0
  File::Slurp: 0
  GD: 2.44
  Graphics::Color::RGB: 0
  HTML::Lint: 0
  JSON::XS: 0
  LWP::Protocol::Net::Curl: 0
  LWP::UserAgent: 0
  List::Compare: 0
  List::MoreUtils: 0
  Log::Dispatch::File: 0
  Log::Log4perl: 1.34
  MIME::Lite: 0
  MRO::Compat: 0
  MongoDB: 0
  Monitoring::Availability: 0.4
  Monitoring::Livestatus: 0.74
  Monitoring::Livestatus::Class: 0.03
  Moose: 0
  Net::HTTP: 6.02
  PDF::Reuse: 0
  Perl::Critic::Policy::Dynamic::NoIndirect: 0
  Perl::Critic::Policy::NamingConventions::ProhibitMixedCaseSubs: 0
  Perl::Critic::Policy::ValuesAndExpressions::ProhibitAccessOfPrivateData: 0
  Plack::Handler::CGI: 0
  Storable: 0
  Template: 0
  Template::Plugin::Date: 0
  Test::Cmd: 0
  Test::JavaScript: 0
  Test::Perl::Critic: 0
  Test::Pod: 1.4
  Test::Pod::Coverage: 0
  Tie::IxHash: 0
  URI::Escape: 0
  WWW::Mechanize::Firefox: 0
  namespace::autoclean: 0
  parent: 0
  perl: 5.8.0
resources:
  bugtracker: http://github.com/sni/Thruk/issues
  homepage: http://www.thruk.org
  license: http://opensource.org/licenses/gpl-3.0.html
  repository: http://github.com/sni/Thruk
version: 1.64
